[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]
autobins = false
edition = "2018"

[lib]
name = "app"
path = "src/frontend/main.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.55"
yew = "0.10.0"
